Feature/epic
Light-it-labs/user-stories pull request #4
Opened 2021-01-14 16:46 UTC by fernfalcnico

Add feature to create, edit and delete epics and user-stories. Some Projects files were modified to start using VueRouter to handle projects pages.

2021-01-14 19:59 UTC, martinopp requested changes
Tambien esta muy bien! A nivel generico, estructura, convenciones, etc. deje algunos comentarios de las cosas mas "gruesas" para optimizar, refactorear, etc.

2021-01-14 19:59 UTC, martinopp commented on app/Http/Controllers/EpicController.php
> +        //Ahora esta harcodeado el usuario xq no tengo merge con la rama con auth:api. Una vez que haga el merge,
Todo codigo o comentario deberia ser en ingles, aunque sea momentaneo para que quede uniforme y entendible para cualquiera.

2021-01-14 19:59 UTC, martinopp commented on resources/js/components/EpicEditor.vue
> +    if('epic' in this.$route.params){
Esta logica dentro del mounted queda un poco confusa. Ver la forma de simplificar la cadena de ifs, o si no se puede, extraer en metodos para que quede mas claro a la lectura de codigo.

2021-01-14 19:59 UTC, martinopp commented on resources/js/components/ProjectIndex.vue
> +            <button @click="$router.push({name: 'Create-Project'})" type="button" class="basicButton">New Project</button>
Para el nombre de las rutas en general se usa una convencion especifica. Es decir, 'createProject' o 'create-project'. Esta bueno mantener las convenciones. Aca Vue.js detalla algunas alternativas. https://vuejs.org/v2/guide/components-registration.html#Name-Casing 

Estoy hilando fino pero el tema de Clean Code cuando el proyecto empieza a crecer es crucial.

2021-01-14 19:59 UTC, martinopp commented on resources/js/components/UserStoryForm.vue
> +        if(response.status === 200 && response.data.success === true){
En este tipo de llamados con axios podemos evitarnos el if utilizando la estructura misma de la llamada. Ejemplos aqui: https://vuejs.org/v2/cookbook/using-axios-to-consume-apis.html

usando el '.then' si fue success o el '.catch' si hubo algun error.

2021-01-14 19:59 UTC, martinopp commented on resources/js/editorTools.js
> +      endpoint: 'http://127.0.0.1:8000/', // Your backend endpoint for url data fetching
Aca el endpoint no deberia estar harcoded. Quizas obtenerlo de de un archivo de constantes (Constants.js)

2021-01-15 12:46 UTC, fernfalcnico commented on resources/js/components/EpicEditor.vue
> +    if('epic' in this.$route.params){
Totalmente de acuerdo. Siempre pongo todo en ingles, claramente me colgue con esto

2021-01-15 12:52 UTC, fernfalcnico commented on resources/js/components/ProjectIndex.vue
> +            <button @click="$router.push({name: 'Create-Project'})" type="button" class="basicButton">New Project</button>
Perfecto!

2021-01-15 12:55 UTC, fernfalcnico commented on resources/js/editorTools.js
> +      endpoint: 'http://127.0.0.1:8000/', // Your backend endpoint for url data fetching
Mal yo. Fue un archivo que me quedo de cuando pensaba usar EditorJs la libreria de Uri. Ya lo saqué. Igual me quedo con el comentario para futuro de obtener el endpoint dinamico y no harcoded.

2021-01-15 12:56 UTC, fernfalcnico commented on app/Http/Controllers/EpicController.php
> +        //Ahora esta harcodeado el usuario xq no tengo merge con la rama con auth:api. Una vez que haga el merge,
Totalmente de acuerdo. Siempre pongo todo en ingles, claramente me colgue con esto

2021-01-15 13:21 UTC, fernfalcnico commented on resources/js/components/EpicEditor.vue
> +    if('epic' in this.$route.params){
El primer if evalua si ya tengo la epica para evitar hacer la request innecesariamente. Todo el else, lo cambie a una funcion afuera para que quede mas limpio y evaluo si hacer la request o es una epica nueva y no hago request.

2021-01-15 13:55 UTC, merged